# yamllint disable rule:line-length
---
name: "Upload to SF"
inputs:
  DMGS:
    required: true
    type: string
  UPLOADS:
    required: true
    type: string
  SF_LOGIN:
    required: true
    type: string
runs:
  using: "composite"
  steps:
    - name: "Upload DMGs to SourceForge"
      id: upload
      shell: bash
      run: |
        UPLOADS=${{ inputs.UPLOADS }}
        DMGs=${{ inputs.DMGS }
        nDMGS=${#DMGS[@]}
        SCP_CMD="scp -o StrictHostKeyChecking=no"
        for (( ii = 0; $ii < $nDMGS; ii++ )); do
          echo "Uploading $"
          sh -c "${SCP_CMD} \"${DMG[$ii]}\" \"${UPLOADS[$ii]}\""
        done
    - name: "Clean up ssh keys"
      id: cleanup_ssh
      shell: bash
      if: ${{ always() }}
      continue-on-error: true
      run: |
        # for ephemeral runners, this stup is unnecessary...
        rm -Rf ~/.ssh
