# yamllint disable rule:line-length
---
name: "Upload to SF"
inputs:
  DMG_W:
    required: true
    type: string
  DMG_WO:
    required: true
    type: string
  DEST_W:
    required: true
    type: string
  DEST_WO:
    required: true
    type: string
  SF_LOGIN:
    required: true
    type: string
runs:
  using: "composite"
  steps:
    - name: "Setup scp command"
      id: scp_setup
      shell: bash
      run: |
        SCP_CMD="scp -o StrictHostKeyChecking=no"
        echo "SCP_CMD=${SCP_CMD}" >> $GITHUB_ENV
    - name: "Upload DMGs to SourceForge"
      id: upload
      shell: bash
      run: |
        echo "Uploading DMG with plugins"
        sh -c "${SCP_CMD} \"${{ inputs.DMG_W }}\" \"${{ inputs.DEST_W }}\""
    - name: "Upload DMGs to SourceForge"
      id: upload
      shell: bash
      run: |
        echo "Uploading DMG without plugins"
        sh -c "${SCP_CMD} \"${{ inputs.DMG_W }}\" \"${{ inputs.DEST_W }}\""
    - name: "Clean up ssh keys"
      id: cleanup_ssh
      shell: bash
      if: ${{ always() }}
      continue-on-error: true
      run: |
        # for ephemeral runners, this stup is unnecessary...
        rm -Rf ~/.ssh
