# yamllint disable rule:line-length
---
name: "Monitor and Build MythTV"

on:  # yamllint disable-line rule:truthy
  schedule:
    - cron: '0 0 * * 0'
    - cron: '0 0 1 * *'
  workflow_dispatch:  # workflow_dispatch allows this to be triggered manually
    inputs:
      text_to_print:
        description: 'Manual trigger'
jobs:
  check-mythtv:
    runs-on: 'macos-latest'
    env:
      MASTER_BRANCH: "master"
      FIXES_BRANCH: "fixes/35"
    outputs:
      MASTER_BRANCH: ${{ env.MASTER_BRANCH }}
      UPDATE_MASTER: ${{ env.UPDATE_MASTER }}
      FIXES_BRANCH: ${{ env.FIXES_BRANCH }}
      UPDATE_FIXES: ${{ env.UPDATE_FIXES }}
    steps:
      - uses: actions/checkout@master
      - name: "Setup environmental variables"
        id: set-env-vars
        run: |
          echo "GIT_CACHE_DIR=$HOME/mythtv" >> $GITHUB_ENV
          echo "DAY_OF_MONTH=$(date +'%d')" >> $GITHUB_ENV
          if [ $DAY_OF_MONTH==1 ]; then
            echo "USE_PAID_RUNNERS=true >> $GITHUB_OUTPUT
          else
            echo "USE_PAID_RUNNERS=false >> $GITHUB_OUTPUT
          fi
      - name: "Setup Mythtv Repo Cache"
        id: cache
        env:
          cache-name: mythtv
        uses: actions/cache@master
        with:
          path: ${{ env.GIT_CACHE_DIR }}
          key: mythtv-git-${{ github.sha }}
          restore-keys: mythtv-git-
      - name: "Check master git repository for updates"
        id: gitcheck_master
        uses: ./.github/actions/git_check
        with:
          BRANCH: ${{ env.MASTER_BRANCH }}
          GIT_CACHE_DIR: ${{ env.GIT_CACHE_DIR }}
      - name: Check ${{ env.FIXES_BRANCH }} git repository for updates
        id: gitcheck_fixes
        uses: ./.github/actions/git_check
        with:
          BRANCH: ${{ env.FIXES_BRANCH }}
          GIT_CACHE_DIR: ${{ env.GIT_CACHE_DIR }}
      - name: Set Update Outputs
        id: set_update_vars
        run: |
          echo "UPDATE_MASTER=${{ steps.gitcheck_master.outputs.UPDATED }}" >> $GITHUB_ENV
          echo "UPDATE_FIXES=${{ steps.gitcheck_fixes.outputs.UPDATED }}" >> $GITHUB_ENV
  build-mythtv-master-cmake:
    needs: check-mythtv
    if: needs.check-mythtv.outputs.UPDATE_MASTER == 'true'
    uses: ./.github/workflows/build_sign_upload.yml
    with:
      MYTHBRANCH: ${{ needs.check-mythtv.outputs.MASTER_BRANCH }}
      BUILDTYPE: production
      BUILD_13: true
      BUILD_14: true
      BUILD_15: true
      BUILD_26: true
      ARCHITECTURE: all
      USE_PAID_RUNNERS: ${{ needs.set-env-vars.outputs.USE_PAID_RUNNERS }}
    secrets: inherit
  build-mythtv-fixes-cmake:
    needs: check-mythtv
    if: needs.check-mythtv.outputs.UPDATE_FIXES == 'true'
    uses: ./.github/workflows/build_sign_upload.yml
    with:
      MYTHBRANCH: ${{ needs.check-mythtv.outputs.FIXES_BRANCH }}
      BUILDTYPE: production
      BUILD_13: true
      BUILD_14: true
      BUILD_15: true
      BUILD_26: true
      ARCHITECTURE: all
      USE_PAID_RUNNERS: ${{ needs.set-env-vars.outputs.USE_PAID_RUNNERS }}
    secrets: inherit
