# yamllint disable rule:line-length
---
name: "Monitor and Build MythTV"

on:  # yamllint disable-line rule:truthy
  schedule:
    - cron: '0 0 * * 0'
    - cron: '0 0 1 * *'
  workflow_dispatch:  # workflow_dispatch allows this to be triggered manually
    inputs:
      FORCE_BUILD:
        type: boolean
        default: false
        description: "Force Build"
jobs:
  check-mythtv:
    runs-on: 'macos-latest'
    env:
      MASTER_BRANCH: "master"
      FIXES_BRANCH: "fixes/35"
      USE_PAID_RUNNERS: false
    outputs:
      MASTER_BRANCH: ${{ env.MASTER_BRANCH }}
      UPDATE_MASTER: ${{ env.UPDATE_MASTER }}
      UPDATE_MASTER_PAID: ${{ env.UPDATE_MASTER_PAID }}
      FIXES_BRANCH: ${{ env.FIXES_BRANCH }}
      UPDATE_FIXES: ${{ env.UPDATE_FIXES }}
      UPDATE_FIXES_PAID: ${{ env.UPDATE_FIXES_PAID }}
    steps:
      - uses: actions/checkout@master
      - name: "Setup environmental variables"
        id: set-env-vars
        run: |
          echo "GIT_CACHE_DIR=$HOME/mythtv" >> $GITHUB_ENV
          echo "DAY_OF_MONTH=$(date +'%d')" >> $GITHUB_ENV
          if [ $DAY_OF_MONTH = 1 ]; then
            echo "USE_PAID_RUNNERS=true" >> $GITHUB_ENV
          fi
      - name: "Setup Mythtv Repo Cache"
        id: cache
        env:
          cache-name: mythtv
        uses: actions/cache@master
        with:
          path: ${{ env.GIT_CACHE_DIR }}
          key: mythtv-git-${{ github.sha }}
          restore-keys: mythtv-git-
      - name: "Check master git repository for updates"
        id: gitcheck_master
        uses: ./.github/actions/git_check
        with:
          BRANCH: ${{ env.MASTER_BRANCH }}
          GIT_CACHE_DIR: ${{ env.GIT_CACHE_DIR }}
      - name: Check ${{ env.FIXES_BRANCH }} git repository for updates
        id: gitcheck_fixes
        uses: ./.github/actions/git_check
        with:
          BRANCH: ${{ env.FIXES_BRANCH }}
          GIT_CACHE_DIR: ${{ env.GIT_CACHE_DIR }}
      - name: Set Update Outputs
        id: set_update_vars
        run: |
          UPDATE_MASTER=${{ steps.gitcheck_master.outputs.UPDATED }}
          UPDATE_FIXES=${{ steps.gitcheck_fixes.outputs.UPDATED }}
          if [ $UPDATE_MASTER && ${USE_PAID_RUNNERS} == 'true' ]; then
            UPDATE_MASTER_PAID=true
          fi
          if [ $UPDATE_FIXES && ${USE_PAID_RUNNERS} == 'true' ]; then
            UPDATE_FIXES_PAID=true
          fi
          # force overide
          if ${FORCE_BUILD}; then
            UPDATE_MASTER=true
            UPDATE_FIXES=true
          fi
          # debug output
          echo "UPDATE_MASTER=$UPDATE_MASTER"
          echo "UPDATE_FIXES=$UPDATE_FIXES"
          echo "UPDATE_MASTER_PAID=$UPDATE_MASTER_PAID"
          echo "UPDATE_FIXES_PAID=$UPDATE_FIXES_PAID"
          # instrument environmental vars
          echo "UPDATE_MASTER=$UPDATE_MASTER" >> $GITHUB_ENV
          echo "UPDATE_FIXES=$UPDATE_FIXES" >> $GITHUB_ENV
          echo "UPDATE_MASTER_PAID=$UPDATE_MASTER_PAID" >> $GITHUB_ENV
          echo "UPDATE_FIXES_PAID=$UPDATE_FIXES_PAID" >> $GITHUB_ENV
  build-mythtv-master-cmake:
    needs: check-mythtv
    if: needs.check-mythtv.outputs.UPDATE_MASTER == 'true'
    uses: ./.github/workflows/build_sign_upload.yml
    with:
      USE_CCACHE: true
      MYTHBRANCH: ${{ needs.check-mythtv.outputs.MASTER_BRANCH }}
      BUILDTYPE: production
      BUILD_13_X86_64: true
      BUILD_14_X86_64: false
      BUILD_14_ARM64: true
      BUILD_15_X86_64: false
      BUILD_15_ARM64: true
      BUILD_26_ARM64: true
    secrets: inherit
  build-mythtv-fixes-cmake:
    needs: check-mythtv
    if: needs.check-mythtv.outputs.UPDATE_FIXES == 'true'
    uses: ./.github/workflows/build_sign_upload.yml
    with:
      USE_CCACHE: true
      MYTHBRANCH: ${{ needs.check-mythtv.outputs.FIXES_BRANCH }}
      BUILDTYPE: production
      BUILD_13_X86_64: true
      BUILD_14_X86_64: false
      BUILD_14_ARM64: true
      BUILD_15_X86_64: false
      BUILD_15_ARM64: true
      BUILD_26_ARM64: true
    secrets: inherit
  build-mythtv-master-paid:
    needs: check-mythtv
    if: needs.check-mythtv.outputs.MASTER_BRANCH_PAID == 'true'
    uses: ./.github/workflows/build_sign_upload.yml
    with:
      USE_CCACHE: true
      MYTHBRANCH: ${{ needs.check-mythtv.outputs.MASTER_BRANCH }}
      BUILDTYPE: production
      BUILD_13_X86_64: false
      BUILD_14_X86_64: true
      BUILD_14_ARM64: false
      BUILD_15_X86_64: false
      BUILD_15_ARM64: false
      BUILD_26_ARM64: false
    secrets: inherit
  build-mythtv-fixes-paid:
    needs: check-mythtv
    if: needs.check-mythtv.outputs.UPDATE_FIXES_PAID == 'true'
    uses: ./.github/workflows/build_sign_upload.yml
    with:
      USE_CCACHE: true
      MYTHBRANCH: ${{ needs.check-mythtv.outputs.FIXES_BRANCH }}
      BUILDTYPE: production
      BUILD_13_X86_64: false
      BUILD_14_X86_64: true
      BUILD_14_ARM64: false
      BUILD_15_X86_64: false
      BUILD_15_ARM64: false
      BUILD_26_ARM64: false
    secrets: inherit