# yamllint disable rule:line-length
---
name: "Monitor and Build MythTV"
run-name: "monitor"

on:  # yamllint disable-line rule:truthy
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:  # workflow_dispatch allows this to be triggered manually
    inputs:
      text_to_print:
        description: 'Manual trigger'
jobs:
  check-mythtv:
    runs-on: 'macos-latest'
    env:
      MASTER_BRANCH: "master"
      FIXES_BRANCH: "fixes/35"
      FIXES_LEGACY_BRANCH: "fixes/34"
    outputs:
      MASTER_BRANCH: ${{ env.MASTER_BRANCH }}
      FIXES_BRANCH: ${{ env.FIXES_BRANCH }}
      FIXES_LEGACY_BRANCH: ${{ env.FIXES_LEGACY_BRANCH }}
    steps:
      - uses: actions/checkout@master
      - name: "Setup environmental variables"
        run: |
          echo "GIT_CACHE_DIR=$HOME/mythtv" >> $GITHUB_ENV
      - name: "Setup Mythtv Repo Cache"
        id: cache
        env:
          cache-name: mythtv
        uses: actions/cache@master
        with:
          path: ${{ env.GIT_CACHE_DIR }}
          key: mythtv-git-${{ github.sha }}
          restore-keys: mythtv-git-
      - name: "Check master git repository for updates"
        id: gitcheck_master
        uses: ./.github/actions/git_check
        with:
          BRANCH: ${{ env.MASTER_BRANCH }}R }}
      - name: "Check ${{ env.FIXES_LEGACY_BRANCH }} git repository for updates"
        id: gitcheck_fixes
        uses: ./.github/actions/git_check
        with:
          BRANCH: ${{ env.FIXES_BRANCH }}
          UPDATE_VAR: ${{ env.UPDATE_FIXES }}
      - name: "Check ${{ env.FIXES_LEGACY_BRANCH }} repository for updates"
        id: gitcheck_fixes_legacy
        uses: ./.github/actions/git_check
        with:
          BRANCH: ${{ env.FIXES_LEGACY_BRANCH }}
          UPDATE_VAR: ${{ env.UPDATE_FIXES_LEGACY }}
  build-mythtv-fixes-cmake:
    needs: check-mythtv
    if: steps.gitcheck_master.outputs.UPDATED == 'true'
    uses: ./.github/workflows/build_sign_upload_cmake.yml
    with:
      MYTHBRANCH: ${{ needs.check-mythtv.outputs.FIXES_BRANCH }}
    secrets: inherit
  build-mythtv-master-cmake:
    needs: check-mythtv
    if: steps.gitcheck_fixes.outputs.UPDATED == 'true'
    uses: ./.github/workflows/build_sign_upload_cmake.yml
    with:
      MYTHBRANCH: ${{ needs.check-mythtv.outputs.MASTER_BRANCH }}
    secrets: inherit
  build-mythtv-fixes-legacy:
    needs: check-mythtv
    if: steps.gitcheck_fixes_legacy.outputs.UPDATED == 'true'
    uses: ./.github/workflows/build_sign_upload.yml
    with:
      MYTHBRANCH: ${{ needs.check-mythtv.outputs.FIXES_LEGACY_BRANCH }}
    secrets: inherit
